Py3 update to README
Per #1 brozzler requires py3.

When I run the command for pip in the README on OS X, I get:
```
Collecting brozzler[easy]
  Using cached brozzler-1.1b5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/04/3w_t28hj0413fnmf2szpzqsh00010g/T/pip-build-3BBLdS/brozzler/setup.py", line 40, in <module>
        long_description=open('README.rst', encoding='UTF-8').read(),
    TypeError: 'encoding' is an invalid keyword argument for this function
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/04/3w_t28hj0413fnmf2szpzqsh00010g/T/pip-build-3BBLdS/brozzler/
```

Changing the command to pip3 allows brozzler to be installed.